# Generated by Django 4.2.5 on 2023-10-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("authname", models.CharField(max_length=30)),
                ("img", models.ImageField(blank=True, null=True, upload_to="blog")),
                ("timeStamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
